foo: ffffffffffffff222222222222233333333

spring:
  rabbitmq:
    host: 192.168.63.128
    port: 5672
    username: admin
    password: 123456
    virtual-host: /hd
    
management:
    endpoints:
        web:
            exposure:
                include: bus-refresh


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

