foo: ffffffffffffff2222222222222

spring:
  rabbitmq:
    host: 192.168.63.128
    port: 5672
    username: admin
    password: 123456
    virtual-host: /hd
    
management:
  endpoints:
    web:
      exposure:
        exclude: bus-refresh
        include: '*'
  endpoint:
     health:
        show-details: always
  server:
      port: 9510
               

